Repository milieuinfo/webcomponent-vl-ui-http-error-message, pull requests merged in 2020-04, with the labels that each got.

#16 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#21 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#22 Introductie 500 foutmelding
  demo/vl-http-error-message.html
  dist/vl-http-error-message.js
  dist/vl-http-error-message.min.js
  dist/vl-http-error-message.src.js
  src/vl-http-error-message.js
  test/e2e/http-error-message.test.js
  test/e2e/pages/vl-http-error-message.page.js
  test/unit/vl-http-error-message.test.html
Labels: enhancement
